# Generated by Django 3.2.5 on 2021-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(max_length=25)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('debug', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='WeekActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('protocol', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'WeekActivity',
                'verbose_name_plural': 'WeekActivities',
            },
        ),
    ]
